---
title: "Dataset 'Salaries' - Analisis Estadistico - UDLA - MDS"
author: "Jorge Melendez B."
date: "27 de mayo de 2024"
output:
  html_document:
    toc: true
    toc_depth: 3
    collapsed: true
    smooth_scroll: true
    theme: cosmo
    highlight: kate
    df_print: paged
    code_folding: show
  word_document:
    toc: true
    toc_depth: '3'
  pdf_document:
    toc: true
    toc_depth: '3'
---

A continuación se presentará un análisis realizado de la clase "**Análisis Estadístico**", combinado con lo aprendido en "**Programación en R**".

```{r warning=FALSE, message=FALSE}
#Librerias utilizadas en el analisis.
library(readxl)
library(ggplot2)
library(ggthemes)
library(corrplot)
library(tidyverse)
library(skimr)
```

## Base de Datos - Set de datos a analizar.

`Este set muestra los sueldos de los profesionales de la rama de ciencia de datos.`

```{r}
sueldos <- read.csv("salaries.csv", sep = ";")
sueldos$salary_in_usd_mm <- sueldos$salary_in_usd / 1000
```

```{r}
# dim(sueldos) # dimensiones del conjunto de datos
# names(sueldos) # nombres de las columnas
# str(sueldos) # estructura del conjunto de datos
# summary(sueldos) # resumen estadístico del conjunto de datos
skim(sueldos)
```

```{r}
sueldos
```

```{r, fig.align="center", label='Histrograma'}
ggplot(sueldos, aes(x=work_year)) + geom_histogram(binwidth = 0.5) + 
  labs(
      title = "Sueldos Profesionales Data Science", # Título del gráfico
      #subtitle = "", # Subtítulo del gráfico
      #caption = "", # Nota al pie del gráfico
      x = "Año", # Etiqueta del eje X
      y = "Sueldo en Dolares" # Etiqueta del eje Y
      ) + 
  theme_economist()
```

```{r, fig.align="center"}
ggplot(sueldos, aes(x=employment_type, y=salary_in_usd_mm)) + geom_boxplot() +
 theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
 theme(plot.margin = margin(t = 20, r = 50, b = 40, l = 10)) +
 theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5)) +
 labs(
      title = "Sueldos en MM Dolares", 
      subtitle = "", 
      caption = "(CT: Contract, FL: Freelance, FT: Fulltime, PT: Partime)", 
      x = "Tipo de Contrato", # Etiqueta del eje X
      y = "Sueldo en Dolares" # Etiqueta del eje Y
      ) +
  theme(plot.title = element_text(hjust = 0.5))+
  theme_economist()
```
```{r, fig.align="center"}
ggplot(sueldos, aes(x=experience_level, y=salary_in_usd_mm)) + geom_boxplot() +
 theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
 theme(plot.margin = margin(t = 20, r = 50, b = 40, l = 10)) +
 theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5)) +
 labs(
      title = "Sueldos en MM Dolares", # Título del gráfico
      subtitle = "", # Subtítulo del gráfico
      caption = "(EN: Entry, EX: Experto, MI: Middle, SE: Senior)", # Nota al pie del gráfico
      x = "Experiencia Laboral", # Etiqueta del eje X
      y = "Sueldo en Miles de Dolares" # Etiqueta del eje Y
      ) +
  theme(plot.title = element_text(hjust = 0.5))+
  stat_boxplot(geom = "errorbar", width = 0.2) +
  theme_economist()
```
```{r}
# creacion de la Desviacion Estandar 
se_sueldos = sd(sueldos$salary_in_usd)
mutate(sueldos, Salary_in_clp = sueldos$salary_in_usd_mm*896)
```


```{r, fig.align="center"}
ggplot(sueldos, aes(x=experience_level, y=salary_in_usd_mm)) + geom_point() +  # Puntos
  geom_errorbar(aes(ymin = salary_in_usd_mm - se_sueldos, ymax = salary_in_usd_mm + se_sueldos), width = 0.2) +  # Barras de error
  labs(title = "Gráfico de Dispersión con Barras de Error",
       x = "Eje X",
       y = "Eje Y")
```

