---
title: "Dataset 'Salaries' - Analisis Estadistico - UDLA - MDS"
author: "Jorge Melendez B."
date: "27 de mayo de 2024"
output:
  html_document:
    toc: true
    toc_depth: 3
    collapsed: true
    smooth_scroll: true
    theme: cosmo
    highlight: kate
    df_print: paged
    code_folding: show
  word_document:
    toc: true
    toc_depth: '3'
---
A continuación se presentará un análisis realizado de la clase "**Análisis Estadístico**", combinado con lo aprendido
en "**Programación en R**". 

```{r message=FALSE, warning=FALSE}
#Librerias utilizadas en el analisis.
library(readxl)
library(ggplot2)
library(ggthemes)
library(corrplot)
library(tidyverse)
```

## Base de Datos - Set de datos a analizar.

```Este set muestra los sueldos de los profesionales de la rama de ciencia de datos.```
```{r}
sueldos <- read.csv("salaries.csv", sep = ";")
sueldos$salary_in_usd_mm <- sueldos$salary_in_usd / 1000
```

```{r}
sueldos
```

```{r}
summary(sueldos)
```

```{r}
ggplot(sueldos, aes(x=work_year ,y=salary_in_usd_mm)) + geom_histogram() + 
  labs(
      title = "Sueldos Profesionales Data Science", # Título del gráfico
      #subtitle = "", # Subtítulo del gráfico
      #caption = "", # Nota al pie del gráfico
      x = "Año", # Etiqueta del eje X
      y = "Sueldo en Dolares" # Etiqueta del eje Y
      )
```


```{r}
ggplot(sueldos, aes(x=employment_type, y=salary_in_usd_mm)) + geom_boxplot() +
 theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
 theme(plot.margin = margin(t = 20, r = 50, b = 40, l = 10)) +
 theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5)) +
 labs(
      title = "Sueldos en MM Dolares", # Título del gráfico
      subtitle = "Por pais", # Subtítulo del gráfico
      #caption = "", # Nota al pie del gráfico
      x = "País", # Etiqueta del eje X
      y = "Sueldo en Miles de Dolares" # Etiqueta del eje Y
      ) +
  theme(plot.title = element_text(hjust = 0.5))
```

